/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SolutionImport } from './routes/solution'
import { Route as ProductImport } from './routes/product'
import { Route as LoginImport } from './routes/login'
import { Route as DetailsImport } from './routes/details'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ComponentsRobotFilterImport } from './routes/components/robotFilter'
import { Route as AuthenticatedAuthenticatedImport } from './routes/_authenticated/_authenticated'
import { Route as AuthenticatedAuthRobotFilterImport } from './routes/_authenticated/_auth.robotFilter'
import { Route as AuthenticatedAuthFleetImport } from './routes/_authenticated/_auth.fleet'
import { Route as AuthenticatedAuthDashboardImport } from './routes/_authenticated/_auth.dashboard'
import { Route as AuthenticatedAuthRobotsTypeImport } from './routes/_authenticated/_auth.robots.$type'
import { Route as AuthenticatedAuthNodesNodeImport } from './routes/_authenticated/_auth.nodes.$node'

// Create/Update Routes

const SolutionRoute = SolutionImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRoute,
} as any)

const ProductRoute = ProductImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DetailsRoute = DetailsImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsRobotFilterRoute = ComponentsRobotFilterImport.update({
  id: '/components/robotFilter',
  path: '/components/robotFilter',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAuthenticatedRoute = AuthenticatedAuthenticatedImport.update(
  {
    id: '/_authenticated/_authenticated',
    getParentRoute: () => rootRoute,
  } as any,
)

const AuthenticatedAuthRobotFilterRoute =
  AuthenticatedAuthRobotFilterImport.update({
    id: '/_authenticated/_auth/robotFilter',
    path: '/robotFilter',
    getParentRoute: () => rootRoute,
  } as any)

const AuthenticatedAuthFleetRoute = AuthenticatedAuthFleetImport.update({
  id: '/_authenticated/_auth/fleet',
  path: '/fleet',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAuthDashboardRoute = AuthenticatedAuthDashboardImport.update(
  {
    id: '/_authenticated/_auth/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRoute,
  } as any,
)

const AuthenticatedAuthRobotsTypeRoute =
  AuthenticatedAuthRobotsTypeImport.update({
    id: '/_authenticated/_auth/robots/$type',
    path: '/robots/$type',
    getParentRoute: () => rootRoute,
  } as any)

const AuthenticatedAuthNodesNodeRoute = AuthenticatedAuthNodesNodeImport.update(
  {
    id: '/_authenticated/_auth/nodes/$node',
    path: '/nodes/$node',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductImport
      parentRoute: typeof rootRoute
    }
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_authenticated': {
      id: '/_authenticated/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/components/robotFilter': {
      id: '/components/robotFilter'
      path: '/components/robotFilter'
      fullPath: '/components/robotFilter'
      preLoaderRoute: typeof ComponentsRobotFilterImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_auth/dashboard': {
      id: '/_authenticated/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAuthDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_auth/fleet': {
      id: '/_authenticated/_auth/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedAuthFleetImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_auth/robotFilter': {
      id: '/_authenticated/_auth/robotFilter'
      path: '/robotFilter'
      fullPath: '/robotFilter'
      preLoaderRoute: typeof AuthenticatedAuthRobotFilterImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_auth/nodes/$node': {
      id: '/_authenticated/_auth/nodes/$node'
      path: '/nodes/$node'
      fullPath: '/nodes/$node'
      preLoaderRoute: typeof AuthenticatedAuthNodesNodeImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_auth/robots/$type': {
      id: '/_authenticated/_auth/robots/$type'
      path: '/robots/$type'
      fullPath: '/robots/$type'
      preLoaderRoute: typeof AuthenticatedAuthRobotsTypeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/details': typeof DetailsRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/solution': typeof SolutionRoute
  '': typeof AuthenticatedAuthenticatedRoute
  '/components/robotFilter': typeof ComponentsRobotFilterRoute
  '/dashboard': typeof AuthenticatedAuthDashboardRoute
  '/fleet': typeof AuthenticatedAuthFleetRoute
  '/robotFilter': typeof AuthenticatedAuthRobotFilterRoute
  '/nodes/$node': typeof AuthenticatedAuthNodesNodeRoute
  '/robots/$type': typeof AuthenticatedAuthRobotsTypeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/details': typeof DetailsRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/solution': typeof SolutionRoute
  '': typeof AuthenticatedAuthenticatedRoute
  '/components/robotFilter': typeof ComponentsRobotFilterRoute
  '/dashboard': typeof AuthenticatedAuthDashboardRoute
  '/fleet': typeof AuthenticatedAuthFleetRoute
  '/robotFilter': typeof AuthenticatedAuthRobotFilterRoute
  '/nodes/$node': typeof AuthenticatedAuthNodesNodeRoute
  '/robots/$type': typeof AuthenticatedAuthRobotsTypeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/details': typeof DetailsRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/solution': typeof SolutionRoute
  '/_authenticated/_authenticated': typeof AuthenticatedAuthenticatedRoute
  '/components/robotFilter': typeof ComponentsRobotFilterRoute
  '/_authenticated/_auth/dashboard': typeof AuthenticatedAuthDashboardRoute
  '/_authenticated/_auth/fleet': typeof AuthenticatedAuthFleetRoute
  '/_authenticated/_auth/robotFilter': typeof AuthenticatedAuthRobotFilterRoute
  '/_authenticated/_auth/nodes/$node': typeof AuthenticatedAuthNodesNodeRoute
  '/_authenticated/_auth/robots/$type': typeof AuthenticatedAuthRobotsTypeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/details'
    | '/login'
    | '/product'
    | '/solution'
    | ''
    | '/components/robotFilter'
    | '/dashboard'
    | '/fleet'
    | '/robotFilter'
    | '/nodes/$node'
    | '/robots/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/details'
    | '/login'
    | '/product'
    | '/solution'
    | ''
    | '/components/robotFilter'
    | '/dashboard'
    | '/fleet'
    | '/robotFilter'
    | '/nodes/$node'
    | '/robots/$type'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/details'
    | '/login'
    | '/product'
    | '/solution'
    | '/_authenticated/_authenticated'
    | '/components/robotFilter'
    | '/_authenticated/_auth/dashboard'
    | '/_authenticated/_auth/fleet'
    | '/_authenticated/_auth/robotFilter'
    | '/_authenticated/_auth/nodes/$node'
    | '/_authenticated/_auth/robots/$type'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DetailsRoute: typeof DetailsRoute
  LoginRoute: typeof LoginRoute
  ProductRoute: typeof ProductRoute
  SolutionRoute: typeof SolutionRoute
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  ComponentsRobotFilterRoute: typeof ComponentsRobotFilterRoute
  AuthenticatedAuthDashboardRoute: typeof AuthenticatedAuthDashboardRoute
  AuthenticatedAuthFleetRoute: typeof AuthenticatedAuthFleetRoute
  AuthenticatedAuthRobotFilterRoute: typeof AuthenticatedAuthRobotFilterRoute
  AuthenticatedAuthNodesNodeRoute: typeof AuthenticatedAuthNodesNodeRoute
  AuthenticatedAuthRobotsTypeRoute: typeof AuthenticatedAuthRobotsTypeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DetailsRoute: DetailsRoute,
  LoginRoute: LoginRoute,
  ProductRoute: ProductRoute,
  SolutionRoute: SolutionRoute,
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  ComponentsRobotFilterRoute: ComponentsRobotFilterRoute,
  AuthenticatedAuthDashboardRoute: AuthenticatedAuthDashboardRoute,
  AuthenticatedAuthFleetRoute: AuthenticatedAuthFleetRoute,
  AuthenticatedAuthRobotFilterRoute: AuthenticatedAuthRobotFilterRoute,
  AuthenticatedAuthNodesNodeRoute: AuthenticatedAuthNodesNodeRoute,
  AuthenticatedAuthRobotsTypeRoute: AuthenticatedAuthRobotsTypeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/details",
        "/login",
        "/product",
        "/solution",
        "/_authenticated/_authenticated",
        "/components/robotFilter",
        "/_authenticated/_auth/dashboard",
        "/_authenticated/_auth/fleet",
        "/_authenticated/_auth/robotFilter",
        "/_authenticated/_auth/nodes/$node",
        "/_authenticated/_auth/robots/$type"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/details": {
      "filePath": "details.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/product": {
      "filePath": "product.tsx"
    },
    "/solution": {
      "filePath": "solution.tsx"
    },
    "/_authenticated/_authenticated": {
      "filePath": "_authenticated/_authenticated.tsx"
    },
    "/components/robotFilter": {
      "filePath": "components/robotFilter.tsx"
    },
    "/_authenticated/_auth/dashboard": {
      "filePath": "_authenticated/_auth.dashboard.tsx"
    },
    "/_authenticated/_auth/fleet": {
      "filePath": "_authenticated/_auth.fleet.tsx"
    },
    "/_authenticated/_auth/robotFilter": {
      "filePath": "_authenticated/_auth.robotFilter.tsx"
    },
    "/_authenticated/_auth/nodes/$node": {
      "filePath": "_authenticated/_auth.nodes.$node.tsx"
    },
    "/_authenticated/_auth/robots/$type": {
      "filePath": "_authenticated/_auth.robots.$type.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
